# Generated by Django 5.0.3 on 2024-03-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0002_rename_userpreferences_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='frequent_used_words',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='lockedKeys',
            field=models.JSONField(default=list),
        ),
    ]
