# Generated by Django 5.0.3 on 2024-03-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0005_alter_preferences_frequent_used_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='frequent_used_words',
            field=models.JSONField(default=[]),
        ),
    ]
