# Generated by Django 5.0.3 on 2024-03-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0011_preferences_color_blind_preferences_high_contrast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='frequent_used_words',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='lockedKeys',
            field=models.JSONField(default=list),
        ),
    ]
