# Generated by Django 5.0.3 on 2024-03-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0012_alter_preferences_frequent_used_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='shortcut_keys',
            field=models.JSONField(default=list),
        ),
    ]
